### ISSUE TITLE
How to build with bundled neon?

### ISSUE THREAD

**Issue by dresco** [notroj/cadaver#7]
Hi, afraid I'm not very good with autoconf, and I can't figure out how to build cadaver against the bundled neon code instead of using the system libraries?

(Am building cadaver with debug symbols to help troubleshoot an embedded web server, and hence want to use the bundled neon for debug info also).. 

Thanks!

**Comment by hughmcmaster** [comment]
If you're building from the latest git source, `cadaver` no longer supports building against the bundled `neon` code.

You'll need to build `neon` yourself, then use the relevant `configure` flags to pass the location of your debug-enabled neon library to `configure`. Run `./configure --help` to find the correct options.

If you're using the latest git version, the build system is broken at the moment due to other issues.

**Comment by dresco** [comment]
> If you're building from the latest git source, `cadaver` no longer supports building against the bundled `neon` code.
> You'll need to build neon yourself, then use the relevant configure flag...

Thanks, appreciate the feedback, apologies for the slow response!
